# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vrowser}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kimoto"]
  s.date = %q{2012-02-06}
  s.default_executable = %q{vrowser}
  s.description = %q{Server browser for many games (Left4Dead2, TeamFortress2, etc)}
  s.email = %q{sub+peerler@gmail.com}
  s.executables = ["vrowser"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/vrowser",
     "examples/config.yml",
     "lib/plugins/l4d2.rb",
     "lib/vrowser/http_daemon.rb",
     "lib/vrowser.rb",
     "test/helper.rb",
     "test/test_vrowser.rb",
"./public_html", "./public_html/css", "./public_html/css/demo_page.css", "./public_html/css/demo_table.css", "./public_html/css/demo_table_jui.css", "./public_html/css/demo_validation.css", "./public_html/css/main.css", "./public_html/css/site_jui.ccss.css", "./public_html/index.html", "./public_html/js", "./public_html/js/jquery-ui-1.8.16.custom.min.js", "./public_html/js/jquery.dataTables.columnFilter.js", "./public_html/js/jquery.dataTables.js", "./public_html/js/jquery.dataTables.min.js", "./public_html/js/jquery.dataTables.nightly.min.js", "./public_html/js/jquery.min.js", "./public_html/js/jquery.tmpl.min.js", "./public_html/js/vrowser.js"]

  s.homepage = %q{http://github.com/kimoto/vrowser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Server browser for many games}
  s.test_files = [
    "test/helper.rb",
     "test/test_vrowser.rb"
  ]

  s.add_dependency 'ruby-qstat'
  s.add_dependency 'sequel'
  s.add_dependency 'retry-handler'
  s.add_dependency 'i18n'
  s.add_dependency 'sqlite3'

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

